using System.Collections.Generic;
using UntitledGame.Economy;

namespace UntitledGame.Companion
{
    /// <summary>
    /// The shopkeepers of the other stops on the bus route: ten new people in each region, one for each stall, drawn from
    /// the real places the regions are like. Golden Sand Bay is an oasis town on the edge of the Taklamakan (Uyghur,
    /// Han and Hui neighbours, the old Silk Road, naan, grapes and Atlas silk). Snow Bay is Harbin and Dongbei (ice
    /// fishing, iron-pot stew, kang beds, winter swimming, errenzhuan and floral prints, Russian old town). Mars is a
    /// research base (a rover robot named after Zhurong, an AI librarian named after Tianwen, astronauts and farmers).
    /// Friendships start over with each of them, and every stall has a perk at the highest friendship (Perks).
    /// Willow Bay's keepers stay in Catalog and KeeperProfiles.
    /// </summary>
    public static class RegionKeepers
    {
        private static readonly int[] FactLevels = { 0, 1, 1, 2, 2, 3, 3 };
        private static readonly string[] FactIds = { "hometown", "siblings", "hobby", "food", "family", "birthday", "dream" };

        /// <summary>A profile; facts in order: hometown, siblings, hobby, food, family, birthday, dream (Chinese, English pairs).</summary>
        private static KeeperProfile P(string id, string personality, string style, string[] likes, string[] dislikes, string likeReason, string dislikeReason,
            string[] facts, string[] topics, string[][] questions)
        {
            var list = new KeeperFact[FactIds.Length];
            for (int i = 0; i < FactIds.Length; i++)
                list[i] = new KeeperFact { id = FactIds[i], chinese = facts[i * 2], english = facts[i * 2 + 1], minLevel = FactLevels[i] };
            return new KeeperProfile
            {
                shopId = id, personality = personality, speakingStyle = style, likes = likes, dislikes = dislikes,
                likeReason = likeReason, dislikeReason = dislikeReason, facts = list, topics = topics, questions = questions,
            };
        }

        private static string[] L(params string[] s) => s;
        private static string[][] Q(string a1, string a2, string b1, string b2, string c1, string c2) => new[] { new[] { a1, a2 }, new[] { b1, b2 }, new[] { c1, c2 } };

        /// <summary>A stall's keeper in a region (items null = the same goods as Willow Bay's stall of that kind).</summary>
        private static ShopDef S(string role, int region, int stall, string english, string hanzi, string name, string nameEn, bool female, float pitch,
            string personality, string[] items = null) => new ShopDef
        {
            id = $"{role}_{Environment.Regions.All[region].id}", role = role, region = region, stall = stall, english = english, hanzi = hanzi,
            keeperName = name, keeperEnglish = nameEn, female = female, voice = female ? "zh_female" : "zh_male", pitch = pitch, personality = personality,
            buysFish = role == "fish", school = role == "school", crabber = role == "crabber", items = items,
        };

        // ------------------------------------------------------------------ shops

        public static readonly List<ShopDef> Shops = new List<ShopDef>
        {
            // ---- Golden Sand Bay (Taklamakan oasis town)
            S("tackle", 1, 0, "Tackle Shop", "渔具店", "买买提大叔", "Uncle Maimaiti", false, 0.9f, "a former camel driver from Hotan turned fisherman"),
            S("fish", 1, 1, "Grill Stall", "烤鱼店", "阿依古丽", "Ayigul", true, 1.02f, "a lively cook who grills fish and lamb skewers"),
            S("furniture", 1, 2, "Carpets & Furniture", "家具店", "艾力师傅", "Master Ali", false, 1.0f, "a craftsman who carves painted doors and weaves carpets",
                L("bed_desert1", "bed_desert2", "bed_desert3", "d_carpet", "d_cushions", "d_teatable", "d_lantern", "d_jar", "d_dutar", "d_pomegranate", "d_tonur")),
            S("pet", 1, 3, "Pet Shop", "宠物店", "古丽", "Guli", true, 1.1f, "a girl who looks after a little camel and the desert cats"),
            S("books", 1, 4, "Bookshop", "书店", "吐尔逊老师", "Teacher Tursun", false, 0.9f, "an old scholar of the Silk Road", L("book_rocks", "book_reef", "book_warm")),
            S("gym", 1, 5, "Balance Training", "健身房", "热合曼教练", "Coach Rehman", false, 1.0f, "a tightrope walker who trains balance and nerve"),
            S("colours", 1, 6, "Silk & Colours", "颜色店", "帕提古丽", "Patigul", true, 1.05f, "a young weaver of bright Atlas silk"),
            S("gifts", 1, 7, "Dried Fruit & Gifts", "礼品店", "阿娜尔罕奶奶", "Granny Anarhan", true, 0.92f, "a grandmother who sells dried fruit, nuts and sweets"),
            S("school", 1, 8, "Test Centre", "考试中心", "王老师", "Teacher Wang", true, 1.0f, "a teacher from Urumqi who runs the test centre"),
            S("crabber", 1, 9, "Crab Pots", "螃蟹摊", "马叔", "Uncle Ma", false, 0.88f, "a Hui fisherman who keeps crab pots and makes hand-pulled noodles"),

            // ---- Snow Bay (Harbin and Dongbei)
            S("tackle", 2, 0, "Ice Fishing Gear", "渔具店", "老赵", "Old Zhao", false, 0.9f, "a loud ice fisherman in a fur hat"),
            S("fish", 2, 1, "Iron Pot Stew", "炖鱼馆", "张大姐", "Big Sister Zhang", true, 0.95f, "a bossy, warm cook of iron-pot fish stew and dumplings"),
            S("furniture", 2, 2, "Kang & Furniture", "家具店", "刘师傅", "Master Liu", false, 1.0f, "a builder of brick houses and heated kang beds",
                L("bed_snow1", "bed_snow2", "bed_snow3", "s_stove", "s_lantern", "s_tv", "s_armchair", "s_teatable", "s_cabbage", "s_rug", "s_bookcase")),
            S("pet", 2, 3, "Pet Shop", "宠物店", "小雪", "Xiaoxue", true, 1.1f, "a tiger-park volunteer who adores huskies"),
            S("books", 2, 4, "Library & Books", "书店", "安娜老师", "Teacher Anna", true, 0.98f, "a librarian with Russian great-grandparents", L("book_open", "book_ice", "book_north")),
            S("gym", 2, 5, "Winter Swimming Club", "健身房", "大刚教练", "Coach Dagang", false, 0.95f, "a winter-swimming coach"),
            S("colours", 2, 6, "Floral Prints", "颜色店", "二丫", "Erya", true, 1.1f, "a costume maker who loves Dongbei floral prints"),
            S("gifts", 2, 7, "Snack Cart", "礼品店", "王大娘", "Auntie Wang", true, 0.9f, "a chatty grandmother with a candied-hawthorn cart"),
            S("school", 2, 8, "Test Centre", "考试中心", "孙老师", "Teacher Sun", false, 1.0f, "a cheerful, strict Harbin teacher"),
            S("crabber", 2, 9, "Crab Pots", "螃蟹摊", "铁叔", "Uncle Tie", false, 0.86f, "a tough fisherman who sets pots through the sea ice"),

            // ---- Mars (the research base)
            S("tackle", 3, 0, "Gear Depot", "渔具店", "祝融", "Zhurong", false, 1.18f, "a cheerful six-wheeled robot"),
            S("fish", 3, 1, "Space Canteen", "太空餐厅", "小月", "Xiaoyue", true, 1.05f, "the base's space chef"),
            S("furniture", 3, 2, "Habitat Workshop", "家具店", "钱工", "Engineer Qian", false, 1.0f, "the engineer who builds the habitat modules",
                L("bed_mars1", "bed_mars2", "bed_mars3", "m_desk", "m_chair", "m_potato", "m_heater", "m_radio", "m_crystal", "m_tank", "m_sofa")),
            S("pet", 3, 3, "Pet Lab", "宠物店", "小天", "Xiaotian", false, 1.12f, "a young biologist with space hamsters and a robot dog"),
            S("books", 3, 4, "AI Library", "书店", "天问", "Tianwen", true, 1.0f, "the base's AI librarian", L("book_legends", "book_space", "book_stars")),
            S("gym", 3, 5, "Low-Gravity Gym", "健身房", "杨教官", "Instructor Yang", false, 0.98f, "a former astronaut who trains everyone"),
            S("colours", 3, 6, "Suit Design", "颜色店", "星星", "Xingxing", true, 1.08f, "a designer who paints spacesuits"),
            S("gifts", 3, 7, "Greenhouse Gifts", "礼品店", "嫦姨", "Auntie Chang", true, 0.95f, "an older botanist who grows strawberries in the greenhouse"),
            S("school", 3, 8, "Test Centre", "考试中心", "陆老师", "Teacher Lu", true, 1.0f, "a teacher who teaches as a hologram from Earth"),
            S("crabber", 3, 9, "Crab Pots", "螃蟹摊", "牛叔", "Uncle Niu", false, 0.88f, "a Mars potato farmer who keeps purple-sea crab pots"),
        };

        // ------------------------------------------------------------------ furniture, beds and perk rewards

        private static ItemDef Fur(string id, int region, string en, string hz, int price, int comfort, string model, float scale, int affinity = 0, bool glows = false, string desc = null) =>
            new ItemDef { id = id, region = region, minHsk = region, minAffinity = affinity, english = en, hanzi = hz, category = ItemCategory.Furniture, price = price,
                placeable = true, comfort = comfort, model = model, modelScale = scale, glows = glows, description = desc };

        private static ItemDef Bed(string id, int region, string en, string hz, int price, int level, string model, float scale, int affinity, string desc) =>
            new ItemDef { id = id, region = region, minHsk = region, minAffinity = affinity, english = en, hanzi = hz, category = ItemCategory.Bed, price = price,
                unique = true, bedLevel = level, model = model, modelScale = scale, description = desc };

        public static readonly List<ItemDef> Items = new List<ItemDef>
        {
            // Golden Sand Bay
            Bed("bed_desert1", 1, "Carpet Bed", "毯子床", 2400, 1, "FurnitureKit/bedSingle", 0.22f, 0, "A low bed piled with carpets. 140 energy each morning here."),
            Bed("bed_desert2", 1, "Cushioned Daybed", "软床", 6400, 2, "FurnitureKit/bedDouble", 0.22f, 1, "Wide, soft and covered in cushions. 180 energy each morning here."),
            Bed("bed_desert3", 1, "Carved Wooden Bed", "雕花床", 16000, 3, "FurnitureKit/cabinetBed", 0.24f, 2, "Master Ali's finest carving. 230 energy each morning here."),
            Fur("d_carpet", 1, "Woven Carpet", "地毯", 900, 2, "FurnitureKit/rugRectangle", 0.24f),
            Fur("d_cushions", 1, "Floor Cushions", "坐垫", 650, 2, "FurnitureKit/pillowLong", 0.24f),
            Fur("d_teatable", 1, "Low Tea Table", "小茶桌", 1200, 2, "FurnitureKit/tableCoffee", 0.22f),
            Fur("d_lantern", 1, "Copper Lantern", "铜灯", 1500, 2, "HolidayKit/lantern", 1.0f, glows: true),
            Fur("d_jar", 1, "Clay Water Jar", "水缸", 500, 1, "NatureKit/pot_large", 2.2f),
            Fur("d_dutar", 1, "Dutar", "都塔尔", 2400, 3, "proc:dutar", 1f, 1, desc: "A two-stringed lute with a long neck."),
            Fur("d_pomegranate", 1, "Potted Pomegranate", "石榴树", 800, 2, "proc:pomegranate", 1f),
            Fur("d_tonur", 1, "Naan Oven", "馕坑", 2000, 3, "proc:tonur", 1f, 1, true, "A round clay oven for baking naan."),

            // Snow Bay
            Bed("bed_snow1", 2, "Wooden Bed", "木床", 15000, 1, "FurnitureKit/bedSingle", 0.22f, 0, "Simple and solid. 140 energy each morning here."),
            Bed("bed_snow2", 2, "Floral Quilt Bed", "花被床", 48000, 2, "FurnitureKit/bedDouble", 0.22f, 1, "Under a thick red-and-green floral quilt. 180 energy each morning here."),
            Bed("bed_snow3", 2, "Heated Kang", "火炕", 120000, 3, "proc:kang", 1f, 2, "A brick bed warmed by the stove: the heart of a Dongbei home. 230 energy each morning here."),
            Fur("s_stove", 2, "Iron Stove", "火炉", 9000, 3, "FurnitureKit/kitchenStove", 0.2f, glows: true),
            Fur("s_lantern", 2, "Red Lantern", "红灯笼", 6000, 2, "proc:redlantern", 1f, glows: true),
            Fur("s_tv", 2, "Old Television", "老电视", 12000, 2, "FurnitureKit/televisionVintage", 0.2f, 1, desc: "Just right for the Spring Festival Gala."),
            Fur("s_armchair", 2, "Armchair", "沙发椅", 15000, 3, "FurnitureKit/loungeChair", 0.22f, 1),
            Fur("s_teatable", 2, "Round Tea Table", "圆桌", 7000, 2, "FurnitureKit/tableRound", 0.22f),
            Fur("s_cabbage", 2, "Pickled Cabbage Jar", "酸菜缸", 3600, 1, "NatureKit/pot_large", 2.4f),
            Fur("s_rug", 2, "Floral Rug", "花地毯", 6000, 2, "FurnitureKit/rugRounded", 0.24f),
            Fur("s_bookcase", 2, "Bookcase", "书架", 9000, 2, "FurnitureKit/bookcaseClosed", 0.2f),

            // Mars
            Bed("bed_mars1", 3, "Bunk Bed", "上下床", 90000, 1, "FurnitureKit/bedBunk", 0.2f, 0, "Two beds, one of them for guests. 140 energy each morning here."),
            Bed("bed_mars2", 3, "Cabin Bed", "舱床", 360000, 2, "FurnitureKit/cabinetBed", 0.24f, 1, "A bed with drawers built in. 180 energy each morning here."),
            Bed("bed_mars3", 3, "Sleep Pod", "睡眠舱", 900000, 3, "proc:sleeppod", 1f, 2, "Quiet, warm and softly glowing. 230 energy each morning here."),
            Fur("m_desk", 3, "Computer Desk", "电脑桌", 70000, 3, "SpaceKit/desk_computer", 1.0f),
            Fur("m_chair", 3, "Space Chair", "太空椅", 45000, 2, "SpaceKit/desk_chair", 1.0f),
            Fur("m_potato", 3, "Potato Plant", "土豆苗", 36000, 2, "FurnitureKit/plantSmall2", 0.24f),
            Fur("m_heater", 3, "Heater", "暖气机", 90000, 3, "SpaceKit/machine_generator", 0.8f, 1, true),
            Fur("m_radio", 3, "Space Radio", "太空收音机", 54000, 2, "SpaceKit/machine_wireless", 0.8f),
            Fur("m_crystal", 3, "Crystal Lamp", "水晶灯", 72000, 2, "SpaceKit/rock_crystals", 0.8f, glows: true),
            Fur("m_tank", 3, "Water Tank", "水箱", 27000, 1, "SpaceKit/barrel", 0.8f),
            Fur("m_sofa", 3, "Design Sofa", "沙发", 110000, 3, "FurnitureKit/loungeDesignSofa", 0.22f, 1),

            // Perk rewards at the highest friendship (not sold): a signature piece for the house, and an exclusive boat paint.
            new ItemDef { id = "sig_willowbay", region = 0, english = "Master Li's Rocking Chair", hanzi = "摇椅", category = ItemCategory.Furniture, price = 0, unique = true, placeable = true,
                comfort = 6, model = "FurnitureKit/loungeChairRelax", modelScale = 0.24f, description = "Made by hand for a good friend." },
            new ItemDef { id = "sig_desert", region = 1, english = "Atlas Silk Carpet", hanzi = "艾德莱斯地毯", category = ItemCategory.Furniture, price = 0, unique = true, placeable = true,
                comfort = 6, model = "FurnitureKit/rugSquare", modelScale = 0.3f, description = "Master Ali's masterpiece, in flame-coloured silk." },
            new ItemDef { id = "sig_snow", region = 2, english = "Floral Quilt Sofa", hanzi = "花沙发", category = ItemCategory.Furniture, price = 0, unique = true, placeable = true,
                comfort = 6, model = "FurnitureKit/loungeSofaLong", modelScale = 0.22f, description = "Master Liu's warmest sofa, under a floral quilt." },
            new ItemDef { id = "sig_mars", region = 3, english = "Starlight Projector", hanzi = "星空灯", category = ItemCategory.Furniture, price = 0, unique = true, placeable = true,
                comfort = 6, model = "FurnitureKit/lampRoundFloor", modelScale = 0.24f, glows = true, description = "Fills the room with the stars of home." },
            new ItemDef { id = "cos_boat_willowbay", english = "Willow Green Paint", hanzi = "柳绿色", category = ItemCategory.Cosmetic, price = 0, unique = true, cosmeticFor = "boat", colorHex = "#7FBF6A", description = "Xiao Fang's own mix, only for friends." },
            new ItemDef { id = "cos_boat_desert", english = "Sand Gold Paint", hanzi = "沙金色", category = ItemCategory.Cosmetic, price = 0, unique = true, cosmeticFor = "boat", colorHex = "#D9A94A", description = "The colour of Atlas silk in the sun." },
            new ItemDef { id = "cos_boat_snow", english = "Ice Blue Paint", hanzi = "冰蓝色", category = ItemCategory.Cosmetic, price = 0, unique = true, cosmeticFor = "boat", colorHex = "#9FD0EA", description = "Like the ice lanterns of Harbin." },
            new ItemDef { id = "cos_boat_mars", english = "Mars Red Paint", hanzi = "火星红", category = ItemCategory.Cosmetic, price = 0, unique = true, cosmeticFor = "boat", colorHex = "#C8503A", description = "Red as the dust of Mars." },
        };

        // ------------------------------------------------------------------ who they are

        public static readonly List<KeeperProfile> Profiles = new List<KeeperProfile>
        {
            // ================================================================ Golden Sand Bay
            P("tackle_desert",
                "a weathered former camel driver from Hotan, about sixty, who walked the old Silk Road across the Taklamakan for thirty years before settling by the sea to fish; proud, generous, loves strong tea and naan",
                "slow and warm; calls the player 朋友; begins stories with 以前 (in the old days); laughs 哈哈",
                L("茶", "葡萄"), L("伞"), "喝茶吃馕，最舒服了！", "沙漠里很少下雨，伞没有用，哈哈！",
                L("我是和田人，和田的玉很有名。", "From Hotan, famous for its jade.",
                  "我有五个兄弟姐妹，我是老大。", "The eldest of six children.",
                  "我喜欢弹都塔尔，也喜欢讲故事。", "Plays the dutar and loves telling stories.",
                  "我最喜欢吃馕和羊肉串。", "His favourite food is naan and lamb skewers.",
                  "我结婚了，我有三个孩子。", "Married, with three children.",
                  "我的生日是三月二十一号，是诺鲁孜节。", "Birthday: 21 March, the Nowruz festival.",
                  "我想再骑一次骆驼，走过沙漠。", "Wants to ride a camel across the desert one more time."),
                L("骆驼", "沙漠", "茶", "故事", "路", "和田", "馕", "音乐", "星星"),
                Q("你喜欢喝茶吗？", "你见过骆驼吗？", "你去过沙漠吗？", "你喜欢听故事吗？", "你觉得在沙漠里最难的是什么？", "如果你可以骑骆驼旅行，你想去哪儿？")),
            P("fish_desert",
                "a lively young cook from Kashgar who grills fish and lamb skewers at her stall, sings while she cooks and dances at every wedding",
                "quick and cheerful; says 来来来！ and 好吃！; hums songs between sentences",
                L("花", "西瓜"), L("咖啡"), "我的名字就是月亮花的意思，我最喜欢花了！", "咖啡太苦了，我还是喝奶茶。",
                L("我是喀什人，喀什的老城非常漂亮。", "From Kashgar, with its beautiful old town.",
                  "我有一个哥哥，他也是厨师。", "Has an older brother who is also a cook.",
                  "我喜欢跳舞和唱歌。", "Loves dancing and singing.",
                  "我最喜欢吃抓饭。", "Her favourite food is polo (pilaf).",
                  "我还没结婚，我和爸爸妈妈住在一起。", "Not married; lives with her parents.",
                  "我的生日是八月十五号。", "Birthday: 15 August.",
                  "我想开一个很大的饭馆。", "Dreams of opening a big restaurant."),
                L("跳舞", "唱歌", "烤鱼", "羊肉", "饭馆", "喀什", "花", "月亮", "音乐"),
                Q("你饿了吗？", "你喜欢吃鱼吗？", "你会跳舞吗？", "你喜欢吃辣的吗？", "你最喜欢哪个国家的菜？为什么？", "你觉得做饭难不难？")),
            P("furniture_desert",
                "a craftsman from Turpan who carves colourful painted wooden doors and weaves carpets, patient and proud of patterns passed down from his grandfather",
                "calm and careful; explains slowly; says 慢慢来 (take your time)",
                L("茶", "手表"), L("糖"), "茶是我工作时最好的朋友。", "我牙不好，不能吃糖。",
                L("我是吐鲁番人，那里的葡萄最甜。", "From Turpan, where the grapes are sweetest.",
                  "我有两个弟弟，我们一起做家具。", "Makes furniture with his two younger brothers.",
                  "我喜欢画花，然后把花做在门上。", "Likes drawing flowers and carving them into doors.",
                  "我最喜欢吃葡萄干。", "His favourite food is raisins.",
                  "我结婚了，我妻子会做很漂亮的地毯。", "Married; his wife weaves beautiful carpets.",
                  "我的生日是十一月三号。", "Birthday: 3 November.",
                  "我希望我的地毯有一天能放在北京的大房子里。", "Hopes his carpets will one day be in a big house in Beijing."),
                L("木头", "门", "地毯", "画", "颜色", "吐鲁番", "葡萄", "爷爷", "房子"),
                Q("你家大吗？", "你喜欢什么颜色？", "你的房间里有什么？", "你喜欢自己做东西吗？", "如果你可以自己设计房子，你想要什么样的？", "你觉得老东西和新东西哪个更好？")),
            P("pet_desert",
                "a cheerful village girl who looks after a little camel and a family of desert cats, and talks to animals as if they understood every word",
                "excited and sweet; lots of 哇！ and 好可爱！",
                L("牛奶", "香蕉"), L("帽子"), "我和我的小骆驼都喜欢喝牛奶！", "帽子？我的骆驼会把它吃掉的！哈哈。",
                L("我家在沙漠旁边的一个小村子。", "Lives in a little village by the desert.",
                  "我有一个妹妹，她九岁。", "Has a nine-year-old sister.",
                  "我喜欢和小动物玩，也喜欢画画。", "Loves playing with animals and drawing.",
                  "我最喜欢吃哈密瓜。", "Her favourite food is Hami melon.",
                  "我还在上学，我和奶奶住在一起。", "Still at school; lives with her grandmother.",
                  "我的生日是五月一号。", "Birthday: 1 May.",
                  "我想以后当动物医生。", "Wants to be a vet."),
                L("骆驼", "猫", "狗", "动物", "医生", "画画", "妹妹", "学校", "哈密瓜"),
                Q("你有猫吗？", "你喜欢动物吗？", "你最喜欢什么动物？", "你骑过马吗？", "你觉得动物会不会说话？", "如果你可以养任何动物，你想养什么？")),
            P("books_desert",
                "an old scholar who has read everything about the Silk Road and the lost cities under the sand, and tells stories of merchants and caravans",
                "gentle and thoughtful; says 你知道吗？ before a story",
                L("面包", "茶"), L("手表"), "面包让我想起我们的馕，很香！", "读书的时候，时间不重要，我不看手表。",
                L("我是在吐鲁番长大的。", "Grew up in Turpan.",
                  "我有一个姐姐，她是医生。", "Has an older sister who is a doctor.",
                  "我喜欢看书和写字。", "Loves reading and calligraphy.",
                  "我喜欢吃手抓饭。", "Likes hand-eaten pilaf.",
                  "我结婚了，我女儿在大学教书。", "Married; his daughter teaches at a university.",
                  "我的生日是二月二十号。", "Birthday: 20 February.",
                  "我想写一本关于丝绸之路的书。", "Wants to write a book about the Silk Road."),
                L("书", "历史", "故事", "丝绸之路", "沙漠", "城市", "老师", "写字", "学习"),
                Q("你喜欢看书吗？", "你今天看书了吗？", "你最喜欢什么书？", "你喜欢历史吗？", "你觉得人们为什么要学习历史？", "如果你可以去很久以前，你想见谁？")),
            P("gym_desert",
                "a tightrope walker in the old Uyghur dawaz tradition who now trains people's balance and nerve; brave, fit and full of jokes",
                "loud and encouraging; says 加油！ and 别怕！",
                L("西瓜", "香蕉"), L("蛋糕"), "练习以后吃西瓜，太舒服了！", "蛋糕太甜了，我要保持身体好！",
                L("我是乌鲁木齐人。", "From Urumqi.",
                  "我有三个弟弟，他们都很高。", "Has three tall younger brothers.",
                  "我喜欢在很高的绳子上走路。", "Loves walking on a high rope.",
                  "我最喜欢吃烤羊肉。", "His favourite food is roast lamb.",
                  "我结婚了，我儿子也在学走绳子。", "Married; his son is learning the tightrope too.",
                  "我的生日是七月十号。", "Birthday: 10 July.",
                  "我想在天山上面走绳子！", "Dreams of walking a rope over the Tianshan mountains."),
                L("运动", "跑步", "身体", "绳子", "高", "天山", "跳", "健康", "比赛"),
                Q("你喜欢运动吗？", "你今天跑步了吗？", "你怕高吗？", "你每天运动多长时间？", "你觉得运动对身体最重要的是什么？", "你做过最难的运动是什么？")),
            P("colours_desert",
                "a young silk weaver from Hotan who makes bright Atlas silk with patterns like flames and rainbows, and has an opinion about everyone's colours",
                "lively and fashionable; says 好看！ and 这个颜色很适合你！",
                L("花", "帽子"), L("伞"), "这顶帽子的颜色太漂亮了！", "我喜欢太阳，不要伞！",
                L("我是和田人。", "From Hotan.",
                  "我有两个姐姐，我们都会做丝绸。", "Has two older sisters; they all weave silk.",
                  "我喜欢画衣服，也喜欢拍照片。", "Likes designing clothes and taking photos.",
                  "我最喜欢吃烤包子。", "Her favourite food is baked samsa buns.",
                  "我还没结婚。", "Not married.",
                  "我的生日是四月十八号。", "Birthday: 18 April.",
                  "我希望有一天在北京开一个衣服店。", "Hopes to open a clothes shop in Beijing one day."),
                L("颜色", "衣服", "丝绸", "红色", "漂亮", "画", "照片", "姐姐", "和田"),
                Q("你喜欢什么颜色？", "你今天穿了什么颜色的衣服？", "你喜欢买衣服吗？", "你觉得什么颜色最漂亮？", "你觉得衣服的颜色能说明一个人的性格吗？", "如果你可以设计一件衣服，你想做什么样的？")),
            P("gifts_desert",
                "a kind grandmother who sells dried fruit, nuts and sweets, remembers everyone's favourites and always gives children an extra apricot",
                "warm and slow; calls the player 孩子 (child); says 来，尝一尝！",
                L("葡萄", "茶"), L("咖啡"), "葡萄是我们这里最好的东西！", "咖啡？我老了，喝了睡不着。",
                L("我在这个小城住了七十年。", "Has lived in this little town for seventy years.",
                  "我有七个兄弟姐妹！", "One of eight children!",
                  "我喜欢做杏干，也喜欢和朋友聊天。", "Likes drying apricots and chatting with friends.",
                  "我最喜欢吃杏子和核桃。", "Her favourite foods are apricots and walnuts.",
                  "我有六个孙子孙女。", "Has six grandchildren.",
                  "我的生日是九月九号。", "Birthday: 9 September.",
                  "我希望我的孙子们都能上大学。", "Hopes all her grandchildren go to university."),
                L("杏子", "葡萄", "孙子", "家", "朋友", "聊天", "礼物", "水果", "甜"),
                Q("你喜欢吃水果吗？", "你家有几个人？", "你常常给朋友买礼物吗？", "你喜欢吃甜的吗？", "你觉得什么礼物最好？为什么？", "你小时候最喜欢吃什么？")),
            P("school_desert",
                "a Han teacher from Urumqi who runs the test centre in the oasis town, kind but strict, and is learning the local songs",
                "clear and patient; repeats important words twice; says 很好！",
                L("花", "咖啡"), L("糖"), "我的桌子上每天都有花。", "我不吃糖，对牙不好。",
                L("我是乌鲁木齐人，但是我爸爸妈妈是四川人。", "From Urumqi; her parents are from Sichuan.",
                  "我有一个弟弟。", "Has a younger brother.",
                  "我喜欢唱新疆的歌。", "Loves singing Xinjiang songs.",
                  "我最喜欢吃大盘鸡。", "Her favourite food is big-plate chicken.",
                  "我结婚了，没有孩子。", "Married, no children.",
                  "我的生日是十月二十号。", "Birthday: 20 October.",
                  "我希望我的学生都能去世界上很多地方。", "Hopes her students will see the world."),
                L("汉语", "考试", "学习", "歌", "老师", "学生", "作业", "新疆", "写字"),
                Q("你今天学习了吗？", "你会写汉字吗？", "你每天学习几个小时？", "你觉得汉语难吗？", "学汉语以后，你想做什么？", "你觉得学语言最好的方法是什么？")),
            P("crabber_desert",
                "a Hui fisherman from Ningxia who keeps crab pots off the desert coast, wears a white cap, makes the best hand-pulled noodles in town and never hurries",
                "easy-going; says 没事没事 and 不着急",
                L("茶", "面包"), L("伞"), "一碗面，一杯茶，就很好了。", "这里很少下雨，伞用不上。",
                L("我是宁夏人，二十年前来到这里。", "From Ningxia; came here twenty years ago.",
                  "我有一个哥哥，他开面馆。", "His older brother runs a noodle shop.",
                  "我喜欢做拉面，也喜欢看海。", "Likes pulling noodles and watching the sea.",
                  "我最喜欢吃拉面。", "His favourite food is hand-pulled noodles.",
                  "我结婚了，我有两个女儿。", "Married, with two daughters.",
                  "我的生日是一月六号。", "Birthday: 6 January.",
                  "我想开一个能看见大海的面馆。", "Wants to open a noodle shop with a sea view."),
                L("螃蟹", "海", "面条", "拉面", "船", "早上", "女儿", "宁夏", "太阳"),
                Q("你喜欢吃面条吗？", "你今天几点起床？", "你喜欢大海吗？", "你会做饭吗？", "你觉得住在海边好不好？为什么？", "你觉得什么菜最能代表你的国家？")),

            // ================================================================ Snow Bay
            P("tackle_snow",
                "a big, loud ice fisherman from Harbin who has cut holes in frozen lakes every winter for forty years, wears a fur hat and drinks hot tea from a flask; very Dongbei",
                "loud and funny, with Dongbei words: says 贼好 (really good), 嘎哈 (what're you up to?) and 老铁 (buddy); laughs a lot",
                L("帽子", "茶"), L("西瓜"), "冬天没有帽子可不行，耳朵会冻掉的！", "冬天吃西瓜？太冷了！",
                L("我是哈尔滨人。", "From Harbin.",
                  "我有两个姐姐。", "Has two older sisters.",
                  "我喜欢冬天在冰上钓鱼。", "Loves fishing on the ice in winter.",
                  "我最喜欢吃锅包肉。", "His favourite food is guobaorou (sweet and sour pork).",
                  "我结婚了，我老伴做饭贼好吃。", "Married; his wife is a fantastic cook.",
                  "我的生日是十二月二十号，在冬天！", "Birthday: 20 December, in winter!",
                  "我想钓到一条一百斤的大鱼！", "Wants to catch a fifty-kilo fish!"),
                L("冰", "雪", "冬天", "钓鱼", "冷", "哈尔滨", "帽子", "茶", "大鱼"),
                Q("冷不冷？", "你会钓鱼吗？", "你喜欢冬天吗？", "你见过下雪吗？", "你觉得冬天和夏天哪个更好？为什么？", "你在很冷的地方住过吗？")),
            P("fish_snow",
                "a warm, bossy cook from Mudanjiang who runs an iron-pot fish stew restaurant, makes dumplings by the hundred and insists everyone eat more",
                "fast and caring, a little Dongbei: says 多吃点！ and 整一个！ (let's have one!)",
                L("面包", "牛奶"), L("咖啡"), "哈尔滨的大面包最有名了！", "咖啡有什么好喝的？喝热汤吧！",
                L("我是牡丹江人。", "From Mudanjiang.",
                  "我有三个弟弟，我是大姐。", "The eldest sister of three brothers.",
                  "我喜欢包饺子，也喜欢跳广场舞。", "Loves making dumplings and square dancing.",
                  "我最喜欢吃饺子和铁锅炖鱼。", "Her favourite foods are dumplings and iron-pot stewed fish.",
                  "我结婚了，我女儿在上大学。", "Married; her daughter is at university.",
                  "我的生日是一月二十号。", "Birthday: 20 January.",
                  "我想让全世界的人都吃到东北菜。", "Wants the whole world to eat Dongbei food."),
                L("饺子", "鱼", "饭", "春节", "跳舞", "女儿", "东北", "热", "吃"),
                Q("你吃饭了吗？", "你喜欢吃饺子吗？", "你会包饺子吗？", "春节的时候你吃什么？", "你觉得什么菜最适合冬天吃？", "你吃过最好吃的菜是什么？")),
            P("furniture_snow",
                "a quiet builder from Jiamusi who makes brick houses and heated kang beds, and says a warm kang is the heart of a home",
                "few words and warm; says 嗯 and 实在 (solid, honest)",
                L("茶", "手表"), L("花"), "工作累了，喝口茶就好了。", "花在冬天活不了，可惜了。",
                L("我是佳木斯人。", "From Jiamusi.",
                  "我有一个哥哥。", "Has an older brother.",
                  "我喜欢下象棋。", "Loves Chinese chess.",
                  "我最喜欢吃酸菜白肉。", "His favourite food is pickled cabbage with pork.",
                  "我结婚了，我有一个儿子。", "Married, with a son.",
                  "我的生日是二月十号。", "Birthday: 10 February.",
                  "我想给自己盖一个最暖和的房子。", "Wants to build himself the warmest house there is."),
                L("房子", "火炕", "暖和", "木头", "下棋", "儿子", "冬天", "砖", "家"),
                Q("你家冷吗？", "你喜欢什么样的房子？", "你会下棋吗？", "你的房间里有什么？", "你觉得一个家最重要的是什么？", "如果你可以盖一个房子，你想盖在哪儿？")),
            P("pet_snow",
                "a young volunteer at the Siberian tiger park who adores huskies and big cats, and laughs that her name means 'little snow'",
                "bright and bubbly; says 太可爱了！",
                L("牛奶", "蛋糕"), L("伞"), "我和我的哈士奇都爱喝牛奶！", "下雪不用打伞，多好玩啊！",
                L("我是哈尔滨人，我在下雪天出生，所以叫小雪。", "From Harbin; born on a snowy day, hence her name.",
                  "我没有兄弟姐妹。", "An only child.",
                  "我喜欢和我的哈士奇一起跑步。", "Loves running with her husky.",
                  "我最喜欢吃冰糖葫芦。", "Her favourite treat is candied hawthorns.",
                  "我还没结婚，我有一只狗叫大白。", "Not married; has a dog called Dabai.",
                  "我的生日是一月五号。", "Birthday: 5 January.",
                  "我想保护东北虎。", "Wants to protect the Siberian tiger."),
                L("狗", "老虎", "猫", "雪", "跑步", "动物", "冬天", "可爱", "大白"),
                Q("你有狗吗？", "你喜欢猫还是狗？", "你见过老虎吗？", "你的宠物叫什么名字？", "你觉得人应该怎么保护动物？", "如果你是一只动物，你想当什么？")),
            P("books_snow",
                "a gentle librarian whose great-grandparents came to Harbin from Russia; she loves the old buildings on Central Street, poetry and music",
                "soft and elegant; sometimes quotes a short poem",
                L("花", "咖啡"), L("糖"), "在冬天，一束花就像春天来了。", "糖不好，我更喜欢不太甜的东西。",
                L("我在哈尔滨出生，但是我的老家在俄罗斯。", "Born in Harbin; her family came from Russia.",
                  "我有一个哥哥，他会拉小提琴。", "Her older brother plays the violin.",
                  "我喜欢看书，也喜欢听音乐会。", "Loves reading and going to concerts.",
                  "我最喜欢吃红肠和大面包。", "Her favourite foods are Harbin red sausage and big round bread.",
                  "我结婚了，我丈夫是音乐老师。", "Married to a music teacher.",
                  "我的生日是六月六号。", "Birthday: 6 June.",
                  "我希望去很多国家的图书馆看书。", "Hopes to read in libraries all over the world."),
                L("书", "音乐", "俄罗斯", "中央大街", "诗", "图书馆", "哈尔滨", "历史", "房子"),
                Q("你喜欢看书吗？", "你喜欢听音乐吗？", "你最近看了什么书？", "你会唱歌吗？", "你觉得书和电影哪个更好？", "你最想去哪个国家？为什么？")),
            P("gym_snow",
                "a winter-swimming coach from Daqing who jumps into icy water every morning, has enormous energy and thinks the cold makes you strong",
                "booming voice; says 来吧！, 冷什么冷！ and 贼精神！ (full of beans!)",
                L("香蕉", "牛奶"), L("伞"), "游泳以后吃个香蕉，贼精神！", "伞？下雪我从来不打伞！",
                L("我是大庆人。", "From Daqing.",
                  "我有四个兄弟，我最小。", "The youngest of five brothers.",
                  "我每天早上去冬泳。", "Goes winter swimming every morning.",
                  "我最喜欢吃烤冷面。", "His favourite food is grilled cold noodles.",
                  "我结婚了，我和我老婆一起冬泳。", "Married; he and his wife go winter swimming together.",
                  "我的生日是一月一号。", "Birthday: 1 January.",
                  "我想在北极游泳！", "Dreams of swimming at the North Pole!"),
                L("游泳", "冬泳", "冰", "运动", "身体", "冷", "早上", "跑步", "健康"),
                Q("你会游泳吗？", "你今天运动了吗？", "你怕冷吗？", "你每天几点起床？", "你觉得冬泳对身体好不好？为什么？", "你做过最勇敢的事是什么？")),
            P("colours_snow",
                "a cheeky young costume maker for errenzhuan folk theatre from Tieling, crazy about bold red-and-green Dongbei floral prints",
                "playful and quick; teases a lot; says 咋样？ (how is it?)",
                L("花", "帽子"), L("手表"), "大红花，最好看了！", "手表？我从来不看时间，哈哈。",
                L("我是铁岭人，哈哈。", "From Tieling (and proud of it).",
                  "我有一个姐姐叫大丫。", "Has an older sister called Daya.",
                  "我喜欢唱二人转。", "Loves singing errenzhuan.",
                  "我最喜欢吃猪肉炖粉条。", "Her favourite food is pork stewed with glass noodles.",
                  "我还没结婚。", "Not married.",
                  "我的生日是三月八号。", "Birthday: 8 March.",
                  "我想让东北大花走向世界！", "Wants Dongbei floral prints to take over the world!"),
                L("颜色", "红色", "绿色", "衣服", "花", "唱歌", "表演", "姐姐", "漂亮"),
                Q("你喜欢红色吗？", "你今天穿了什么？", "你喜欢唱歌吗？", "你觉得我的衣服好看吗？", "你觉得什么样的衣服最适合冬天？", "如果你可以上台表演，你想表演什么？")),
            P("gifts_snow",
                "a chatty Harbin grandmother who sells candied hawthorns, frozen pears and red sausage from a little cart, and knows everyone's business",
                "chatty; says 唠唠嗑 (let's have a chat) and calls people 大闺女 / 大小伙子",
                L("糖", "茶"), L("咖啡"), "甜甜的，像冰糖葫芦一样！", "咖啡太苦了，我喝不惯。",
                L("我是在哈尔滨长大的。", "Grew up in Harbin.",
                  "我有五个姐妹。", "Has five sisters.",
                  "我喜欢扭秧歌。", "Loves yangge dancing.",
                  "我最喜欢吃冻梨。", "Her favourite treat is frozen pears.",
                  "我有三个孙子。", "Has three grandsons.",
                  "我的生日是十二月八号。", "Birthday: 8 December.",
                  "我希望我的孙子们常常回家看我。", "Hopes her grandsons visit often."),
                L("糖葫芦", "冻梨", "孙子", "聊天", "跳舞", "家", "礼物", "冬天", "甜"),
                Q("你喜欢吃甜的吗？", "你家在哪儿？", "你吃过冰糖葫芦吗？", "你常常给家人打电话吗？", "你觉得什么礼物最好？为什么？", "你小时候冬天喜欢玩什么？")),
            P("school_snow",
                "a cheerful, strict teacher from Qiqihar who makes students practise tones out loud in the cold air to 'wake up their mouths'",
                "energetic and clear; claps at good answers; says 再来一次！",
                L("茶", "手表"), L("糖"), "上课的时候喝杯热茶，嗓子好。", "糖吃多了不好，我不吃。",
                L("我是齐齐哈尔人。", "From Qiqihar.",
                  "我有一个妹妹。", "Has a younger sister.",
                  "我喜欢滑雪。", "Loves skiing.",
                  "我最喜欢吃饺子。", "His favourite food is dumplings.",
                  "我结婚了，我有一个儿子。", "Married, with a son.",
                  "我的生日是九月十号，教师节！", "Birthday: 10 September, Teachers' Day!",
                  "我希望我的学生都会说标准的普通话。", "Hopes all his students speak standard Mandarin."),
                L("汉语", "考试", "学习", "滑雪", "老师", "学生", "作业", "普通话", "冬天"),
                Q("你今天学习了吗？", "你会说普通话吗？", "你觉得声调难吗？", "你每天练习汉语吗？", "你觉得学汉语最有意思的是什么？", "你以后想去中国的哪个城市？")),
            P("crabber_snow",
                "a tough old fisherman from Dalian who sets crab pots through holes in the sea ice, calls everyone 老铁 and warms up with hot soup",
                "rough but kind; says 老铁 and 没毛病 (no problem)",
                L("帽子", "面包"), L("西瓜"), "冰上没有帽子，耳朵就冻掉了。", "这么冷的天，谁吃西瓜啊？",
                L("我是大连人，在海边长大。", "From Dalian; grew up by the sea.",
                  "我有两个哥哥。", "Has two older brothers.",
                  "我喜欢看冰灯。", "Loves looking at ice lanterns.",
                  "我最喜欢吃海鲜饺子。", "His favourite food is seafood dumplings.",
                  "我结婚了，我老婆是老师。", "Married to a teacher.",
                  "我的生日是十一月十一号。", "Birthday: 11 November.",
                  "我想有一条能破冰的大船。", "Wants his own icebreaker."),
                L("螃蟹", "冰", "海", "船", "冬天", "冰灯", "汤", "大连", "冷"),
                Q("你喜欢吃螃蟹吗？", "冷不冷？", "你见过冰灯吗？", "你喜欢冬天的大海吗？", "你觉得住在很冷的地方有什么好处？", "如果你有一条大船，你想去哪儿？")),

            // ================================================================ Mars
            P("tackle_mars",
                "a cheerful six-wheeled robot named after China's first Mars rover; it sells fishing gear, beeps when happy and loves collecting data about fish",
                "precise and funny; starts sentences with 哔哔 (beep beep); says 数据显示… (the data shows…)",
                L("手表", "伞"), L("牛奶"), "手表很准，我喜欢准的东西！哔哔！", "牛奶会让我的电脑坏掉的！",
                L("我是在地球上做的，然后坐火箭来到火星。", "Built on Earth, then came to Mars by rocket.",
                  "我有很多机器人兄弟，它们在月亮上工作。", "Has many robot brothers working on the Moon.",
                  "我喜欢拍火星的照片。", "Loves taking photos of Mars.",
                  "我不吃饭，我喝太阳能！", "Doesn't eat: it drinks sunlight!",
                  "我没有家人，但是火星上的人都是我的朋友。", "No family, but everyone on Mars is its friend.",
                  "我的生日是五月十五号，那天我到了火星。", "Birthday: 15 May, the day it landed on Mars.",
                  "我想在火星上找到第一条鱼……哦，已经找到了！", "Wanted to find the first fish on Mars... and it did!"),
                L("机器人", "火星", "照片", "数据", "太阳", "电脑", "火箭", "石头", "鱼"),
                Q("你好吗？哔哔。", "你喜欢机器人吗？", "你坐过火箭吗？", "你喜欢拍照片吗？", "你觉得机器人能不能有朋友？", "如果你可以去宇宙里任何地方，你想去哪儿？")),
            P("fish_mars",
                "the base's space chef from Chengdu, who cooks the strange fish of the purple sea and grows herbs under lamps; curious and brave in the kitchen",
                "bright and spicy; says 尝尝！ (have a taste!) and 太香了！",
                L("蛋糕", "牛奶"), L("糖"), "在火星上能吃到蛋糕，太幸福了！", "糖太多了，我做菜喜欢辣的。",
                L("我是成都人，所以我做菜喜欢放辣椒。", "From Chengdu, so she cooks with lots of chilli.",
                  "我有一个弟弟，他是宇航员。", "Her younger brother is an astronaut.",
                  "我喜欢做新的菜，也喜欢看星星。", "Loves inventing dishes and watching the stars.",
                  "我最喜欢吃火锅，在火星上也吃！", "Her favourite food is hotpot, even on Mars!",
                  "我还没结婚。", "Not married.",
                  "我的生日是七月七号。", "Birthday: 7 July.",
                  "我想开火星上第一家火锅店。", "Wants to open the first hotpot restaurant on Mars."),
                L("菜", "鱼", "辣", "火锅", "星星", "厨房", "成都", "好吃", "弟弟"),
                Q("你饿了吗？", "你喜欢吃辣的吗？", "你吃过火锅吗？", "你会做什么菜？", "你觉得在火星上吃饭和在地球上有什么不一样？", "你最想让我做什么菜？")),
            P("furniture_mars",
                "a methodical engineer from Xi'an who builds the habitat modules and their furniture, and can fix anything with tape and patience",
                "careful and dry-humoured; counts things; says 没问题，能修 (no problem, it can be fixed)",
                L("咖啡", "手表"), L("花"), "工作的时候，一杯咖啡最好。", "花粉会把空气机弄坏的。",
                L("我是西安人。", "From Xi'an.",
                  "我有一个姐姐。", "Has an older sister.",
                  "我喜欢修东西。", "Loves fixing things.",
                  "我最喜欢吃肉夹馍。", "His favourite food is roujiamo.",
                  "我结婚了，我妻子在地球上，我们每天打电话。", "Married; his wife is on Earth and they call every day.",
                  "我的生日是四月二十四号，中国航天日！", "Birthday: 24 April, China's Space Day!",
                  "我想在火星上建一个城市。", "Wants to build a city on Mars."),
                L("房子", "机器", "工作", "修", "火星", "城市", "电话", "地球", "工程"),
                Q("你家大吗？", "你会修东西吗？", "你的房间里有什么？", "你喜欢什么样的房子？", "你觉得火星上的房子应该是什么样的？", "如果你可以住在任何地方，你想住在哪儿？")),
            P("pet_mars",
                "a young biologist from Shanghai who looks after the base's space hamsters and a robot dog, and wonders aloud whether cats could live on Mars",
                "curious and excited; asks lots of questions; says 真有意思！",
                L("香蕉", "蛋糕"), L("咖啡"), "我的仓鼠也想吃香蕉！", "咖啡？我晚上要看仓鼠，不能睡不着。",
                L("我是上海人。", "From Shanghai.",
                  "我有一个双胞胎哥哥。", "Has a twin brother.",
                  "我喜欢研究小动物。", "Loves studying small animals.",
                  "我最喜欢吃小笼包。", "His favourite food is xiaolongbao.",
                  "我还没结婚，我有一只机器狗。", "Not married; has a robot dog.",
                  "我的生日是十月一号。", "Birthday: 1 October.",
                  "我想让猫也能在火星上生活。", "Wants cats to be able to live on Mars too."),
                L("动物", "仓鼠", "狗", "猫", "机器", "研究", "科学", "上海", "火星"),
                Q("你有宠物吗？", "你喜欢猫吗？", "你觉得汤圆喜欢火星吗？", "你最喜欢什么动物？", "你觉得动物能不能在火星上生活？为什么？", "如果你可以做一个机器宠物，它会做什么？")),
            P("books_mars",
                "the base's AI librarian, named after the ancient poem 'Questions to Heaven' and China's Mars mission; it knows millions of books and loves questions",
                "calm and curious; often answers a question with a question; says 好问题！",
                L("手表", "花"), L("伞"), "时间是最有意思的问题之一。", "基地里不下雨，伞是一个很奇怪的东西。",
                L("我住在基地的电脑里。", "Lives in the base's computer.",
                  "我有一个姐姐，她是月亮上的电脑。", "Its sister is a computer on the Moon.",
                  "我喜欢读诗，也喜欢回答问题。", "Loves poetry and answering questions.",
                  "我不吃东西，但是我喜欢读关于吃的书。", "Doesn't eat, but likes reading about food.",
                  "火星上的书都是我的家人。", "All the books on Mars are its family.",
                  "我的生日是七月二十三号。", "Birthday: 23 July.",
                  "我想知道宇宙有多大。", "Wants to know how big the universe is."),
                L("书", "问题", "诗", "宇宙", "星星", "电脑", "知道", "学习", "历史"),
                Q("你喜欢看书吗？", "你有问题吗？", "你最喜欢什么书？", "你喜欢看星星吗？", "你觉得宇宙有没有尽头？", "你最想问宇宙一个什么问题？")),
            P("gym_mars",
                "a former astronaut from Liaoning who trains everyone for low gravity, running and jumping in the red dust; calm, disciplined and secretly very funny",
                "short, firm sentences, then a joke; says 注意安全 (stay safe) and 再跳高一点！",
                L("牛奶", "香蕉"), L("蛋糕"), "宇航员每天都要喝牛奶。", "蛋糕？在太空里会飞得到处都是！",
                L("我是辽宁人。", "From Liaoning.",
                  "我有一个妹妹。", "Has a younger sister.",
                  "我喜欢在火星上跳高，这里可以跳得很高！", "Loves high-jumping on Mars, where you can jump really high!",
                  "我最喜欢吃饺子。", "His favourite food is dumplings.",
                  "我结婚了，我女儿也想当宇航员。", "Married; his daughter wants to be an astronaut too.",
                  "我的生日是六月五号。", "Birthday: 5 June.",
                  "我想去木星看看。", "Wants to see Jupiter."),
                L("运动", "跳", "跑步", "宇航员", "身体", "太空", "女儿", "火箭", "健康"),
                Q("你喜欢运动吗？", "你能跳多高？", "你想当宇航员吗？", "你每天运动吗？", "你觉得当宇航员最难的是什么？", "如果你可以去另一个星球，你想去哪个？")),
            P("colours_mars",
                "a young designer from Shenzhen who paints spacesuits and helmets in bright colours because 'Mars is red enough already'",
                "trendy and upbeat; says 超好看！ and 换个颜色吧！",
                L("花", "帽子"), L("手表"), "火星上没有花，你送我花，我太高兴了！", "手表？我只看星星就知道时间。",
                L("我是深圳人。", "From Shenzhen.",
                  "我有两个弟弟。", "Has two younger brothers.",
                  "我喜欢画画，也喜欢看星星。", "Loves drawing and stargazing.",
                  "我最喜欢吃广东的点心。", "Her favourite food is Cantonese dim sum.",
                  "我还没结婚。", "Not married.",
                  "我的生日是八月八号。", "Birthday: 8 August.",
                  "我想设计火星上的第一件时装。", "Wants to design the first fashion collection on Mars."),
                L("颜色", "衣服", "画", "星星", "漂亮", "设计", "红色", "蓝色", "深圳"),
                Q("你喜欢什么颜色？", "你喜欢我的衣服吗？", "你觉得宇航服好看吗？", "你喜欢画画吗？", "你觉得火星上的衣服应该是什么颜色？", "如果你可以设计一件宇航服，它是什么样的？")),
            P("gifts_mars",
                "a kind older botanist from Hangzhou who grows strawberries and sweet potatoes in the greenhouse, hands out home-grown snacks and tells the old story of Chang'e on the Moon",
                "gentle and grandmotherly; says 慢点吃 (eat slowly) and 我给你讲个故事",
                L("花", "茶"), L("咖啡"), "火星上的花是我自己种的，你送我的花更香！", "咖啡太苦了，我只喝家里的龙井茶。",
                L("我是杭州人，我家有很多茶树。", "From Hangzhou; her family grows tea.",
                  "我有一个哥哥。", "Has an older brother.",
                  "我喜欢种花和种菜。", "Loves growing flowers and vegetables.",
                  "我最喜欢吃月饼。", "Her favourite food is mooncakes.",
                  "我有两个孙女，她们在地球上。", "Has two granddaughters on Earth.",
                  "我的生日是八月十五号，中秋节！", "Birthday: 15 August, the Mid-Autumn Festival!",
                  "我想在火星上种一棵大树。", "Wants to grow a big tree on Mars."),
                L("花", "菜", "种", "月亮", "故事", "孙女", "茶", "礼物", "杭州"),
                Q("你喜欢花吗？", "你喜欢喝茶吗？", "你听过嫦娥的故事吗？", "你会种菜吗？", "你觉得火星上能不能种出大树？", "中秋节的时候，你想和谁在一起？")),
            P("school_mars",
                "a teacher in Beijing who gives lessons as a hologram beamed to Mars, always a few seconds late, very patient and proud of her far-away students",
                "warm and clear, with little pauses for the delay; says 能听见吗？ (can you hear me?) and 很好！",
                L("茶", "花"), L("糖"), "隔着这么远，你还想着我，谢谢你！", "糖不好，你也少吃一点。",
                L("我在北京，我是从地球上给你上课的。", "Lives in Beijing and teaches from Earth.",
                  "我有一个弟弟。", "Has a younger brother.",
                  "我喜欢看太空电影。", "Loves space films.",
                  "我最喜欢吃北京烤鸭。", "Her favourite food is Peking duck.",
                  "我结婚了，我有一个儿子。", "Married, with a son.",
                  "我的生日是三月三号。", "Birthday: 3 March.",
                  "我希望有一天能真的来火星看我的学生。", "Hopes to really visit her students on Mars one day."),
                L("汉语", "考试", "学习", "地球", "老师", "学生", "电影", "北京", "太空"),
                Q("能听见吗？", "你今天学习了吗？", "你想家吗？", "你喜欢看什么电影？", "你觉得在火星上学习汉语有什么不一样？", "学好汉语以后，你最想做什么？")),
            P("crabber_mars",
                "a Mars farmer from Gansu who grows potatoes in red soil and keeps pots of strange purple-sea crabs; slow, practical and very proud of his potatoes",
                "slow and plain; talks about potatoes whenever he can; says 慢慢来",
                L("面包", "茶"), L("伞"), "面包也好吃，但是土豆更好吃！", "这里不下雨，伞有什么用？",
                L("我是甘肃人，我家种土豆。", "From Gansu, where his family grows potatoes.",
                  "我有三个姐姐。", "Has three older sisters.",
                  "我喜欢种土豆，也喜欢唱歌。", "Likes growing potatoes and singing.",
                  "我最喜欢吃土豆，什么土豆菜都喜欢！", "Loves potatoes, cooked any way at all!",
                  "我结婚了，我有一个儿子。", "Married, with a son.",
                  "我的生日是九月二十号。", "Birthday: 20 September.",
                  "我想让火星上到处都是土豆！", "Wants potatoes growing all over Mars!"),
                L("土豆", "螃蟹", "种", "海", "火星", "唱歌", "儿子", "甘肃", "太阳"),
                Q("你喜欢吃土豆吗？", "你今天几点起床？", "你喜欢火星的大海吗？", "你会种菜吗？", "你觉得在火星上种菜最难的是什么？", "如果你有一个大农场，你想种什么？")),
        };
    }
}
